/** Каталог видов, источников и правил. Сид кладёт это в PostgreSQL. */

import type {
  BehaviorRow,
  ContextRow,
  Rule,
  SoundRow,
  Source,
  Species,
} from "../../domain/types.js";

export const species: Species[] = [
  {
    id: "cat",
    name: "Кошка",
    latin: "Felis catus",
    logic: "motivational_human",
    logic_label: "Сигнал к человеку, не «слово»",
    logic_note:
      "Взрослое мяу почти не используется между кошками: это запрос к человеку. Тип звука (шипение или мяу) читается увереннее, чем «смысл мяу» без контекста.",
  },
  {
    id: "dog",
    name: "Собака",
    latin: "Canis familiaris",
    logic: "graded_context",
    logic_label: "Сила звука зависит от ситуации",
    logic_note:
      "Лай не слова. Акустика статистически связана с ситуацией (тревога / изоляция / игра), но игра и изоляция похожи. Без контекста и языка тела перевод слабый.",
  },
  {
    id: "chicken",
    name: "Курица",
    latin: "Gallus gallus domesticus",
    logic: "referential",
    logic_label: "Крик указывает на событие",
    logic_note:
      "Пищевой крик и тревоги на воздух или землю обозначают, что случилось: если проиграть запись, куры ищут еду, смотрят вверх или замирают — даже когда причины не видно. Это ближе к переводу, чем лай или мяу.",
  },
];

export const sources: Source[] = [
  {
    id: "ntalampiras2019",
    species_id: "cat",
    authors: "Ntalampiras S. et al.",
    year: 2019,
    title: "Automatic classification of cat vocalizations emitted in different contexts",
    venue: "Animals",
    doi: "10.3390/ani9080543",
    url: "https://doi.org/10.3390/ani9080543",
    how_used:
      "Три ситуации мяу в опыте: ожидание еды, одиночество, расчёсывание. Приложение звук само не распознаёт.",
  },
  {
    id: "nicastro2003",
    species_id: "cat",
    authors: "Nicastro N., Owren M. J.",
    year: 2003,
    title:
      "Classification of domestic cat (Felis catus) vocalizations by naive and experienced human listeners",
    venue: "Journal of Comparative Psychology",
    doi: "10.1037/0735-7036.117.1.44",
    url: "https://doi.org/10.1037/0735-7036.117.1.44",
    how_used:
      "Люди слабо угадывают контекст мяу без видео. Без контекста уверенность специально занижается.",
  },
  {
    id: "schotz2017",
    species_id: "cat",
    authors: "Schötz S., van de Weijer J., Eklund R.",
    year: 2017,
    title: "Phonetic characteristics of domestic cat vocalisations",
    venue: "VIHAR",
    url: "https://vihar-2017.vihar.org/assets/papers/VIHAR-2017_paper_5.pdf",
    how_used:
      "Список типов: мяу, мурлыканье, трель, рычание, шипение, чириканье. Агонистические типы (вой, рычание, шипение, сплёвывание, крик) — в конфликтных ситуациях, в т.ч. при появлении другой кошки.",
  },
  {
    id: "schotz2023",
    species_id: "cat",
    authors: "Schötz S., van de Weijer J., Eklund R.",
    year: 2023,
    title: "Context effects on duration, F0, and intonation in human-directed domestic cat meows",
    venue: "Applied Animal Behaviour Science",
    doi: "10.1016/j.applanim.2023.106146",
    url: "https://doi.org/10.1016/j.applanim.2023.106146",
    how_used: "969 мяу, 7 домашних ситуаций. Еда — самая частая; в переноске высота голоса падает.",
  },
  {
    id: "mccomb2009",
    species_id: "cat",
    authors: "McComb K., Taylor A. M., Wilson C., Charlton B. D.",
    year: 2009,
    title: "The cry embedded within the purr",
    venue: "Current Biology",
    doi: "10.1016/j.cub.2009.05.033",
    url: "https://doi.org/10.1016/j.cub.2009.05.033",
    how_used: "Просительное мурлыканье содержит «крик» ~380 Гц; люди слышат его как более срочное.",
  },
  {
    id: "bradshaw2000",
    species_id: "cat",
    authors: "Bradshaw J., Cameron-Beaumont C.",
    year: 2000,
    title: "The signalling repertoire of the domestic cat and its undomesticated relatives",
    venue: "In: The Domestic Cat (Turner & Bateson)",
    how_used:
      "Взрослое мяу адресовано человеку; запрос обойти препятствие (дверь) — типичная функция.",
  },
  {
    id: "yin2004",
    species_id: "dog",
    authors: "Yin S., McCowan B.",
    year: 2004,
    title: "Barking in domestic dogs: context specificity and individual identification",
    venue: "Animal Behaviour",
    doi: "10.1016/j.anbehav.2003.07.016",
    url: "https://doi.org/10.1016/j.anbehav.2003.07.016",
    how_used:
      "4672 лая, 10 собак, 3 контекста. Тревога: ниже, резче, чаще. Изоляция и игра: выше и тональнее.",
  },
  {
    id: "pongracz2005",
    species_id: "dog",
    authors: "Pongrácz P., Molnár C., Miklósi Á., Csányi V.",
    year: 2005,
    title: "Human listeners are able to classify dog barks recorded in different situations",
    venue: "Journal of Comparative Psychology",
    doi: "10.1037/0735-7036.119.2.136",
    url: "https://doi.org/10.1037/0735-7036.119.2.136",
    how_used: "Люди выше случайности относят лай к ситуации и эмоции.",
  },
  {
    id: "pongracz2006",
    species_id: "dog",
    authors: "Pongrácz P., Molnár C., Miklósi Á.",
    year: 2006,
    title: "Acoustic parameters of dog barks carry emotional information for humans",
    venue: "Applied Animal Behaviour Science",
    doi: "10.1016/j.applanim.2005.12.004",
    url: "https://doi.org/10.1016/j.applanim.2005.12.004",
    how_used: "Низкий частый лай → агрессия; высокий тональный с паузами → страх. Правила Мортона.",
  },
  {
    id: "farago2010",
    species_id: "dog",
    authors: "Faragó T., Pongrácz P., Range F., Virányi Z., Miklósi Á.",
    year: 2010,
    title: "The bone is mine: affective and referential aspects of dog growls",
    venue: "Animal Behaviour",
    doi: "10.1016/j.anbehav.2010.01.005",
    url: "https://doi.org/10.1016/j.anbehav.2010.01.005",
    how_used:
      "Рычание при кости, игре и незнакомце различимо; звук несёт сведения о ситуации, не только об эмоции.",
  },
  {
    id: "morton1977",
    species_id: "dog",
    authors: "Morton E. S.",
    year: 1977,
    title:
      "On the occurrence and significance of motivation-structural rules in some bird and mammal sounds",
    venue: "The American Naturalist",
    doi: "10.1086/283219",
    url: "https://doi.org/10.1086/283219",
    how_used:
      "Низкий резкий звук — враждебность; высокий протяжный — страх или умиротворение. Правило для многих видов.",
  },
  {
    id: "evans1993",
    species_id: "chicken",
    authors: "Evans C. S., Evans L., Marler P.",
    year: 1993,
    title: "On the meaning of alarm calls: functional reference in an avian vocal system",
    venue: "Animal Behaviour",
    doi: "10.1006/anbe.1993.1158",
    url: "https://doi.org/10.1006/anbe.1993.1158",
    how_used:
      "Воздушная тревога — укрытие и взгляд вверх; наземная — вытянутая стойка. Так реагируют на запись, даже без хищника.",
  },
  {
    id: "evans1999",
    species_id: "chicken",
    authors: "Evans C. S., Evans L.",
    year: 1999,
    title: "Chicken food calls are functionally referential",
    venue: "Animal Behaviour",
    doi: "10.1006/anbe.1999.1143",
    url: "https://doi.org/10.1006/anbe.1999.1143",
    how_used: "Если проиграть пищевой крик, куры ищут еду на земле, даже когда корма нет.",
  },
  {
    id: "evans2007",
    species_id: "chicken",
    authors: "Evans C. S., Evans L.",
    year: 2007,
    title: "Representational signalling in birds",
    venue: "Biology Letters",
    doi: "10.1098/rsbl.2006.0561",
    url: "https://doi.org/10.1098/rsbl.2006.0561",
    how_used: "Пищевой крик сообщает о корме, а не просто о возбуждении.",
  },
  {
    id: "schotz2019",
    species_id: "cat",
    authors: "Schötz S.",
    year: 2019,
    title: "Phonetic methods in cat vocalisation studies: A report from the Meowsic project",
    venue: "FONETIK 2019 / Zenodo",
    doi: "10.5281/zenodo.3245999",
    url: "https://doi.org/10.5281/zenodo.3245999",
    how_used:
      "Ситуации: ласка, руки, игра, питьё, охота и др. Типы: вой, крик боли, сплёвывание, брачный крик. Агонистические записи — при введении новой кошки к живущим.",
  },
  {
    id: "marler1986a",
    species_id: "chicken",
    authors: "Marler P., Dufty A., Pickert R.",
    year: 1986,
    title:
      "Vocal communication in the domestic chicken. I. Does a sender communicate information about the quality of a food referent to a receiver?",
    venue: "Animal Behaviour",
    doi: "10.1016/S0003-3472(86)80229-2",
    url: "https://doi.org/10.1016/S0003-3472(86)80229-2",
    how_used:
      "Петух кодирует качество корма: на предпочитаемую пищу пищевых криков больше, чем на непищевой объект.",
  },
  {
    id: "marler1986b",
    species_id: "chicken",
    authors: "Marler P., Dufty A., Pickert R.",
    year: 1986,
    title:
      "Vocal communication in the domestic chicken. II. Is a sender sensitive to the presence and nature of a receiver?",
    venue: "Animal Behaviour",
    doi: "10.1016/S0003-3472(86)80230-9",
    url: "https://doi.org/10.1016/S0003-3472(86)80230-9",
    how_used:
      "Пищевой крик зависит от того, кто рядом: с курицей криков больше, с петухом меньше, в одиночестве ещё меньше.",
  },
];

export const sounds: SoundRow[] = [
  ["cat", "meow", "Мяу", "Рот открывается-закрывается, запрос к человеку"],
  ["cat", "purr", "Мурлыканье", "Низкая вибрация 20–30 Гц; не равно «счастье»"],
  ["cat", "trill", "Трель", "Короткий мягкий рокот при подходе"],
  ["cat", "hiss", "Шипение", "Шумный выдох, зубы видны"],
  ["cat", "growl", "Рычание", "Низкий резкий предупреждающий звук"],
  ["cat", "chirp", "Чириканье", "На добычу за стеклом, не к человеку"],
  ["cat", "howl", "Вой", "Длинный предупреждающий вой, часто с рычанием"],
  ["cat", "snarl", "Крик боли / оскал", "Резкий высокий крик в драке или при боли"],
  ["cat", "spit", "Сплёвывание", "Более резкий вариант шипения"],
  ["cat", "mew", "Тонкое мяу", "Высокое тонкое мяу: котёнок, страдание или покорность"],
  ["cat", "mating", "Брачный крик", "Длинные серии весной, не запрос к хозяину"],
  ["dog", "bark", "Лай", "Повторяющийся крик, сила зависит от ситуации"],
  ["dog", "growl", "Рычание", "Низкий шумный звук"],
  ["dog", "whine", "Скуление", "Высокий протяжный запрос или страдание"],
  ["chicken", "food_call", "Пищевой крик", "Пульсирующие звуки при обнаружении корма"],
  ["chicken", "aerial", "Воздушная тревога", "Высокий тонкий крик на объект сверху"],
  ["chicken", "ground", "Наземная тревога", "Пульсирующий крик на наземную угрозу"],
  ["chicken", "unknown", "Непонятное кудахтанье", "Тип крика не определён"],
];

export const contexts: ContextRow[] = [
  ["cat", "food", "Ждёт еду / кормят"],
  ["cat", "isolation", "Одна в незнакомом месте"],
  ["cat", "brush", "Расчёсывают"],
  ["cat", "door", "У двери или окна"],
  ["cat", "greeting", "Встреча с человеком"],
  ["cat", "carrier", "Переноска / ветклиника"],
  ["cat", "cuddle", "Ласка / гладят"],
  ["cat", "lifting", "Берут на руки / держат"],
  ["cat", "play", "Игра"],
  ["cat", "mating", "Брачный сезон"],
  ["cat", "agonistic", "Конфликт с другой кошкой"],
  ["dog", "disturbance", "Незнакомец / звонок в дверь"],
  ["dog", "isolation", "Оставлена одна, без хозяина"],
  ["dog", "play", "Игра с человеком или собакой"],
  ["dog", "food_guard", "Еда или предмет, который не отдают"],
  ["dog", "stranger", "Приближение незнакомца вплотную"],
  ["dog", "walk", "Собираются на прогулку / поводок"],
  ["dog", "ball", "Показывают мяч или игрушку"],
  ["dog", "fight", "Имитация нападения / защита"],
  ["chicken", "food_found", "Найден корм"],
  ["chicken", "overhead", "Что-то движется сверху"],
  ["chicken", "ground_threat", "Что-то движется по земле"],
  ["chicken", "preferred_food", "Предпочитаемый корм (не просто объект)"],
  ["chicken", "hen_present", "Рядом курица (аудитория)"],
];

export const behaviors: BehaviorRow[] = [
  ["cat", "approach", "Идёт к человеку"],
  ["cat", "tail_up", "Хвост трубой"],
  ["cat", "ears_back", "Уши прижаты"],
  ["cat", "crouch", "Припала, отступает"],
  ["cat", "knead", "«Месит» лапами"],
  ["dog", "play_bow", "Игровой поклон"],
  ["dog", "stiff", "Застыла, вес вперёд"],
  ["dog", "wag_loose", "Свободно виляет хвостом"],
  ["dog", "retreat", "Отступает, оглядывается"],
  ["dog", "at_door", "Стоит у двери"],
  ["chicken", "search_ground", "Ищет на земле"],
  ["chicken", "look_up", "Смотрит вверх / припадает"],
  ["chicken", "vigilant", "Вытянулась, осматривается"],
];

export const rules: Rule[] = [
  {
    id: "cat_hiss",
    species_id: "cat",
    sound_id: "hiss",
    context_id: null,
    behavior_id: null,
    gloss: "«Стой. Не подходи, буду защищаться».",
    function: "Оборонительное предупреждение, увеличить дистанцию",
    state: "Страх / оборонительная агрессия",
    confidence: 0.88,
    why: "В списке типов Шёц шипение — угрожающий выдох, часто на внезапную опасность. Тип звука здесь надёжнее ситуации.",
    not_a_fact: "Это не фраза и не «злость на хозяина» без контекста нападения.",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "cat_growl",
    species_id: "cat",
    sound_id: "growl",
    context_id: null,
    behavior_id: null,
    gloss: "«Не приближайся, конфликт».",
    function: "Предупреждение / отгон",
    state: "Конфликтное возбуждение",
    confidence: 0.84,
    why: "Рычание в описании Шёц — сигнал опасности. Совпадает с правилом Мортона: низкий резкий звук — враждебность.",
    not_a_fact: "Не перевод мысли, а функция угрозы.",
    weak: 0,
    sources: ["schotz2017", "morton1977"],
  },
  {
    id: "cat_trill",
    species_id: "cat",
    sound_id: "trill",
    context_id: null,
    behavior_id: null,
    gloss: "«Привет, подхожу мирно».",
    function: "Дружеский контакт при сближении",
    state: "Дружеский контакт",
    confidence: 0.78,
    why: "Трель у Шёц — приветствие и дружеский подход. Один из самых однозначных мягких сигналов кошки.",
    not_a_fact: "Не доказано как слово «привет»; это типичная функция.",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "cat_chirp",
    species_id: "cat",
    sound_id: "chirp",
    context_id: null,
    behavior_id: null,
    gloss: "Не обращение к вам: охотничья реакция на добычу.",
    function: "Звук на добычу, не к человеку",
    state: "Охотничье возбуждение",
    confidence: 0.74,
    why: "Чириканье в списке типов — реакция на недоступную добычу, не запрос к человеку.",
    not_a_fact: "Не «посмотри, птица» как фраза к хозяину.",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "cat_purr_food",
    species_id: "cat",
    sound_id: "purr",
    context_id: "food",
    behavior_id: null,
    gloss: "«Покорми» — просительное мурлыканье, не обычное «довольство».",
    function: "Запрос корма через срочный акустический компонент",
    state: "Активный запрос еды",
    confidence: 0.8,
    why: "Маккомб и соавт., 2009: в мурлыканье при просьбе о еде встроен высокий «крик» около 380 герц. Люди слышат его как более срочное и менее приятное.",
    not_a_fact: "Обычное мурлыканье так переводить нельзя.",
    weak: 0,
    sources: ["mccomb2009", "schotz2017"],
  },
  {
    id: "cat_purr_any",
    species_id: "cat",
    sound_id: "purr",
    context_id: null,
    behavior_id: null,
    gloss: "Скорее «я не угроза / продолжай», а не «я счастлив».",
    function: "Низкая угроза; может быть при контакте, боли, стрессе, родах",
    state: "Неоднозначно",
    confidence: 0.36,
    why: "Шёц: мурлыкают и при довольстве, и при боли. Без ситуации еды нельзя выбрать просительное чтение Маккомб.",
    not_a_fact: "Не научный факт «кошка счастлива». Данных мало.",
    weak: 1,
    sources: ["schotz2017", "mccomb2009"],
  },
  {
    id: "cat_meow_food",
    species_id: "cat",
    sound_id: "meow",
    context_id: "food",
    behavior_id: null,
    gloss: "«Обрати внимание: ситуация связана с едой».",
    function: "Привлечение человека в контексте корма",
    state: "Предвкушение / требование",
    confidence: 0.66,
    why: "Шёц, 2023: корм — самая частая домашняя ситуация мяу (40%). Нталампирас и соавт., 2019, тоже выделяют ожидание еды. Это функция, не слово «голод».",
    not_a_fact: "Мяу само по себе не значит «хочу есть» (Никастро: люди путают ситуации).",
    weak: 0,
    sources: ["schotz2023", "ntalampiras2019", "nicastro2003"],
  },
  {
    id: "cat_meow_iso",
    species_id: "cat",
    sound_id: "meow",
    context_id: "isolation",
    behavior_id: null,
    gloss: "«Мне плохо: я одна в незнакомом месте».",
    function: "Сигнал страдания к человеку",
    state: "Тревога, неприятная ситуация",
    confidence: 0.64,
    why: "Нталампирас и соавт., 2019: одиночество в незнакомом месте — отдельная опытная ситуация мяу. Не любая жалоба дома.",
    not_a_fact: "Не любая «жалоба» дома.",
    weak: 0,
    sources: ["ntalampiras2019"],
  },
  {
    id: "cat_meow_brush",
    species_id: "cat",
    sound_id: "meow",
    context_id: "brush",
    behavior_id: null,
    gloss:
      "Мяу во время тактильного контакта (расчёсывание). Может быть и запрос продолжить, и «хватит».",
    function: "Вокализация при расчёсывании",
    state: "Контакт; по одному мяу не ясно, приятно или нет",
    confidence: 0.52,
    why: "Нталампирас и соавт., 2019: расчёсывание хозяином — отдельная опытная ситуация. Статья не разделяет «приятно / неприятно».",
    not_a_fact: "Не «мне нравится» как факт.",
    weak: 1,
    sources: ["ntalampiras2019"],
  },
  {
    id: "cat_meow_door",
    species_id: "cat",
    sound_id: "meow",
    context_id: "door",
    behavior_id: null,
    gloss: "«Открой / пропусти».",
    function: "Запрос убрать препятствие",
    state: "Требование к человеку",
    confidence: 0.68,
    why: "Брэдшоу: мяу взрослых — запрос к человеку. Шёц, 2023, выделяет ситуацию «дверь или окно».",
    not_a_fact: "Не словарное «открой».",
    weak: 0,
    sources: ["bradshaw2000", "schotz2023"],
  },
  {
    id: "cat_meow_greeting",
    species_id: "cat",
    sound_id: "meow",
    context_id: "greeting",
    behavior_id: null,
    gloss: "«Я здесь» при встрече. Часто вместе с трелью.",
    function: "Контакт при сближении",
    state: "Дружеский контакт или требование",
    confidence: 0.55,
    why: "Приветственное мяу описано у Шёц. Без трели и языка тела легко спутать с требованием.",
    not_a_fact: "Не словарное «привет».",
    weak: 1,
    sources: ["schotz2017", "schotz2023"],
  },
  {
    id: "cat_meow_carrier",
    species_id: "cat",
    sound_id: "meow",
    context_id: "carrier",
    behavior_id: null,
    gloss: "«Это неприятно, я не хочу здесь быть».",
    function: "Страдание в закрытом месте или у врача",
    state: "Неприятная ситуация",
    confidence: 0.72,
    why: "Шёц, 2023: в переноске высота голоса устойчиво падает, в отличие от еды. Вторая по частоте ситуация в их выборке.",
    not_a_fact: "Не любое недовольство.",
    weak: 0,
    sources: ["schotz2023"],
  },
  {
    id: "cat_meow_only",
    species_id: "cat",
    sound_id: "meow",
    context_id: null,
    behavior_id: null,
    gloss: "Только «кошка адресует звук человеку». Контекст неизвестен.",
    function: "Общий запрос внимания",
    state: "Неизвестно",
    confidence: 0.28,
    why: "Никастро и Оурен, 2003: люди, даже владельцы, плохо угадывают ситуацию мяу без картинки. Без ситуации перевод был бы выдумкой.",
    not_a_fact: "Нельзя выбрать «голод» или «ласка» — данных мало.",
    weak: 1,
    sources: ["nicastro2003"],
  },
  {
    id: "dog_bark_dist",
    species_id: "dog",
    sound_id: "bark",
    context_id: "disturbance",
    behavior_id: null,
    gloss: "«Граница нарушена / чужой у двери».",
    function: "Сигнал тревоги на вторжение",
    state: "Высокое возбуждение, часто с агрессивным компонентом",
    confidence: 0.8,
    why: "Ин и Маккоуэн: лай на звонок незнакомца — ниже, резче, длиннее, чаще. 4672 записи лая, три лабораторные ситуации. Понграц: люди слышат в этом агрессию.",
    not_a_fact: "Не слово «охранник».",
    weak: 0,
    sources: ["yin2004", "pongracz2006"],
  },
  {
    id: "dog_bark_iso",
    species_id: "dog",
    sound_id: "bark",
    context_id: "isolation",
    behavior_id: null,
    gloss: "«Вернись / я один».",
    function: "Зов из одиночества",
    state: "Страх, фрустрация",
    confidence: 0.74,
    why: "Лай в одиночестве в том же наборе записей выше и певучее, чем лай на чужого у двери. Понграц: высокий протяжный лай с длинными паузами люди описывают как страх.",
    not_a_fact: "Акустически близок к игровому — без «оставлена одна» путается.",
    weak: 0,
    sources: ["yin2004", "pongracz2006"],
  },
  {
    id: "dog_bark_play",
    species_id: "dog",
    sound_id: "bark",
    context_id: "play",
    behavior_id: "play_bow",
    gloss: "«Это игра».",
    function: "Игровое возбуждение",
    state: "Приятное возбуждение",
    confidence: 0.7,
    why: "Игра — третья ситуация у Ин. По звуку похоже на одиночество; игровой поклон помогает не спутать со страданием.",
    not_a_fact: "Лай «в игре» без поклона слабее.",
    weak: 0,
    sources: ["yin2004", "pongracz2006"],
  },
  {
    id: "dog_bark_play_weak",
    species_id: "dog",
    sound_id: "bark",
    context_id: "play",
    behavior_id: null,
    gloss: "Возможно игра, но по звуку это же может быть одиночество.",
    function: "Неоднозначно: игра или контактный крик",
    state: "Сильное возбуждение; из лая не ясно, хорошо это или плохо",
    confidence: 0.48,
    why: "Ин: лай в одиночестве и в игре по звуку ближе друг к другу, чем к лаю на чужого. Без языка тела нельзя делать вид, что уверены.",
    not_a_fact: "Не факт «собака веселится».",
    weak: 1,
    sources: ["yin2004"],
  },
  {
    id: "dog_bark_only",
    species_id: "dog",
    sound_id: "bark",
    context_id: null,
    behavior_id: null,
    gloss: "Слышен лай. Без ситуации это не перевод.",
    function: "Неизвестно",
    state: "Неизвестно",
    confidence: 0.3,
    why: "Набор записей Ин имеет смысл только потому, что каждый лай записан в известной ситуации. Один «гав» без ситуации нельзя превратить в слово.",
    not_a_fact: "Фантазия вроде «я охраняю дом» здесь запрещена.",
    weak: 1,
    sources: ["yin2004", "pongracz2005"],
  },
  {
    id: "dog_growl_food",
    species_id: "dog",
    sound_id: "growl",
    context_id: "food_guard",
    behavior_id: null,
    gloss: "«Это моё, не бери».",
    function: "Охрана еды или предмета",
    state: "Защита с угрозой",
    confidence: 0.78,
    why: "Фараго и соавт., 2010: рычание у кости отличается от игрового и от рычания на незнакомца; другие собаки ведут себя так, будто звук сообщает о ситуации.",
    not_a_fact: "Не любая рычалка = охрана еды.",
    weak: 0,
    sources: ["farago2010"],
  },
  {
    id: "dog_growl_play",
    species_id: "dog",
    sound_id: "growl",
    context_id: "play",
    behavior_id: "play_bow",
    gloss: "«Играем грубо, это не драка».",
    function: "Игровое рычание",
    state: "Игровое возбуждение",
    confidence: 0.72,
    why: "Фараго: игровое рычание отличимо, но без игрового поклона легко принять за угрозу.",
    not_a_fact: "Рычание само по себе не «давай играть».",
    weak: 0,
    sources: ["farago2010"],
  },
  {
    id: "dog_growl_stranger",
    species_id: "dog",
    sound_id: "growl",
    context_id: "stranger",
    behavior_id: null,
    gloss: "«Не подходи».",
    function: "Угроза: отойди",
    state: "Агрессия / защита",
    confidence: 0.8,
    why: "Третья ситуация у Фараго плюс правило Мортона: низкий резкий звук — враждебность.",
    not_a_fact: "Не приговор о характере собаки.",
    weak: 0,
    sources: ["farago2010", "morton1977"],
  },
  {
    id: "dog_growl_only",
    species_id: "dog",
    sound_id: "growl",
    context_id: null,
    behavior_id: null,
    gloss: "Низкий резкий звук чаще угроза, но может быть игра.",
    function: "Недостаточно данных, чтобы выбрать одну из трёх ситуаций в статье про рычание",
    state: "Неоднозначно",
    confidence: 0.4,
    why: "Без кости / игры / незнакомца три экспериментальных класса неразличимы. Мортон даёт только направление «тяжелее, чем скуление».",
    not_a_fact: "Не факт нападения.",
    weak: 1,
    sources: ["farago2010", "morton1977"],
  },
  {
    id: "dog_whine",
    species_id: "dog",
    sound_id: "whine",
    context_id: null,
    behavior_id: null,
    gloss: "«Мне плохо / помоги / пусти» — запрос, не атака.",
    function: "Просьба о помощи или расстройство, не нападение",
    state: "Страх / просьба; причина неизвестна",
    confidence: 0.58,
    why: "По Мортону высокий тональный звук — не враждебность. Конкретная причина (боль, дверь, одиночество) из скуления не следует.",
    not_a_fact: "Не диагноз боли.",
    weak: 1,
    sources: ["morton1977", "pongracz2006"],
  },
  {
    id: "chick_food",
    species_id: "chicken",
    sound_id: "food_call",
    context_id: null,
    behavior_id: null,
    gloss: "«Здесь еда».",
    function: "Указание на корм, подзыв других",
    state: "Обнаружение пищи",
    confidence: 0.86,
    why: "Эванс и Эванс, 1999: пищевые крики указывают на корм. Если проиграть запись, куры ищут еду на земле, даже когда её нет. Логика другая, чем у мяу: тип крика и есть содержание.",
    not_a_fact:
      "Не человеческая фраза, но ближайший к переводу случай в этом приложении наряду с тревогами.",
    weak: 0,
    sources: ["evans1999", "evans2007"],
  },
  {
    id: "chick_air",
    species_id: "chicken",
    sound_id: "aerial",
    context_id: null,
    behavior_id: null,
    gloss: "«Сверху опасность — смотри вверх / в укрытие».",
    function: "Воздушная угроза",
    state: "Тревога",
    confidence: 0.84,
    why: "Эванс, Эванс и Марлер, 1993: после проигрывания воздушной тревоги куры чаще бегут в укрытие, припадают и смотрят вверх — без хищника в кадре.",
    not_a_fact: "Не слово «ястреб», а тип угрозы «сверху».",
    weak: 0,
    sources: ["evans1993"],
  },
  {
    id: "chick_ground",
    species_id: "chicken",
    sound_id: "ground",
    context_id: null,
    behavior_id: null,
    gloss: "«На земле опасность — стойка, осмотр».",
    function: "Наземная угроза",
    state: "Тревога",
    confidence: 0.84,
    why: "Тот же опыт с записью: наземная тревога — вытянутая настороженная стойка, не укрытие как при воздухе.",
    not_a_fact: "Не имя конкретного хищника.",
    weak: 0,
    sources: ["evans1993"],
  },
  {
    id: "chick_unknown",
    species_id: "chicken",
    sound_id: "unknown",
    context_id: null,
    behavior_id: null,
    gloss: "Кудахтанье без типа крика перевести нельзя.",
    function: "Неизвестно",
    state: "Неизвестно",
    confidence: 0.2,
    why: "У кур смысл привязан к типу крика. Без выбранного типа это была бы выдумка.",
    not_a_fact: "Любая «расшифровка кудахтанья» здесь запрещена.",
    weak: 1,
    sources: ["evans2007"],
  },
  {
    id: "cat_howl",
    species_id: "cat",
    sound_id: "howl",
    context_id: null,
    behavior_id: null,
    gloss: "«Это угроза на расстоянии» — вой, часто вместе с рычанием.",
    function: "Предупреждение в конфликтной ситуации",
    state: "Конфликтное возбуждение",
    confidence: 0.76,
    why: "Шёц: вой — длинные серии в угрожающей ситуации, часто слиты с рычанием. Не брачный крик, если нет сезона.",
    not_a_fact: "Не «кошка разговаривает».",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_howl_agonistic",
    species_id: "cat",
    sound_id: "howl",
    context_id: "agonistic",
    behavior_id: null,
    gloss: "«Держись на расстоянии» — вой в конфликте с другой кошкой.",
    function: "Агонистическое предупреждение между кошками",
    state: "Конфликт / угроза",
    confidence: 0.84,
    why: "Шёц записывала вой среди агонистических типов при введении новой кошки к уже живущим. Вой часто идёт вместе с рычанием.",
    not_a_fact: "Не просьба к человеку и не брачный крик.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_snarl",
    species_id: "cat",
    sound_id: "snarl",
    context_id: null,
    behavior_id: null,
    gloss: "Крик в драке или при боли. Нужно прекратить действие.",
    function: "Сигнал активной борьбы или боли",
    state: "Сильное страдание или драка",
    confidence: 0.8,
    why: "Шёц: крик боли и оскала — громкий резкий высокий звук прямо до или во время драки, либо при боли.",
    not_a_fact: "Не обычное мяу.",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "cat_snarl_agonistic",
    species_id: "cat",
    sound_id: "snarl",
    context_id: "agonistic",
    behavior_id: null,
    gloss: "Крик / оскал в стычке с другой кошкой — активная борьба или защита.",
    function: "Агонистический крик в драке",
    state: "Драка / сильная защита",
    confidence: 0.86,
    why: "У Шёц snarl (cry, defence screech) входит в набор агонистических записей при конфликте кошек; типично до или во время драки.",
    not_a_fact: "Не «просто громкое мяу» и не доказанная травма без осмотра.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_spit",
    species_id: "cat",
    sound_id: "spit",
    context_id: null,
    behavior_id: null,
    gloss: "«Назад» — более резкая оборонительная реакция, чем шипение.",
    function: "Интенсивная оборонительная угроза",
    state: "Испуг / защита",
    confidence: 0.82,
    why: "В списке типов Шёц сплёвывание — отдельный, более резкий вариант шипения (часто со смычкой в начале).",
    not_a_fact: "Не «злость на хозяина» без угрозы дистанции.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_spit_agonistic",
    species_id: "cat",
    sound_id: "spit",
    context_id: "agonistic",
    behavior_id: null,
    gloss: "«Назад» — резкая оборона в конфликте с другой кошкой.",
    function: "Интенсивная агонистическая угроза",
    state: "Испуг / защита в стычке",
    confidence: 0.86,
    why: "Сплёвывание у Шёц — агонистический тип наряду с шипением и воем; фиксировалось при конфликте кошек.",
    not_a_fact: "Не перевод мысли о хозяине.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_growl_agonistic",
    species_id: "cat",
    sound_id: "growl",
    context_id: "agonistic",
    behavior_id: null,
    gloss: "«Не подходи» — рычание на другую кошку.",
    function: "Агонистическое предупреждение",
    state: "Конфликтное возбуждение",
    confidence: 0.88,
    why: "Рычание — один из основных агонистических типов у Шёц при введении новой кошки; низкий резкий звук согласуется с правилом Мортона.",
    not_a_fact: "Не приговор о характере.",
    weak: 0,
    sources: ["schotz2017", "schotz2019", "morton1977"],
  },
  {
    id: "cat_hiss_agonistic",
    species_id: "cat",
    sound_id: "hiss",
    context_id: "agonistic",
    behavior_id: null,
    gloss: "«Стой» — шипение в конфликте с другой кошкой.",
    function: "Оборонительное предупреждение между кошками",
    state: "Страх / защита",
    confidence: 0.9,
    why: "Шипение входит в агонистический набор Шёц (введение новой кошки). Тип звука здесь надёжный маркер дистанции.",
    not_a_fact: "Не «злость на хозяина» без угрозы.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_mew",
    species_id: "cat",
    sound_id: "mew",
    context_id: null,
    behavior_id: null,
    gloss: "Тонкое высокое мяу: у котёнка — к матери; у взрослой — чаще страдание или покорность.",
    function: "Запрос внимания / сигнал слабости",
    state: "Страдание или покорность; без возраста неоднозначно",
    confidence: 0.56,
    why: "Шёц: тонкое мяу с гласными вроде «и» и «е» — котёнок зовёт мать; взрослые — когда грустно, страдают или показывают покорность. Без возраста уверенность средняя.",
    not_a_fact: "Не отдельное слово «мама».",
    weak: 1,
    sources: ["schotz2017"],
  },
  {
    id: "cat_mew_isolation",
    species_id: "cat",
    sound_id: "mew",
    context_id: "isolation",
    behavior_id: null,
    gloss: "Тонкое мяу в одиночестве: ближе к зову / страданию, чем к обычному мяу у миски.",
    function: "Зов или сигнал страдания при разлуке",
    state: "Тревога / разлука",
    confidence: 0.6,
    why: "Шёц: тонкое мяу — у котёнка к матери, у взрослых при страдании или покорности. Контекст изоляции (в т.ч. от матери/опекуна) есть в разметке Meowsic.",
    not_a_fact: "Не доказанное «мама» и не то же самое, что мяу ожидания еды.",
    weak: 1,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_mating",
    species_id: "cat",
    sound_id: "mating",
    context_id: "mating",
    behavior_id: null,
    gloss: "Брачный крик, не просьба к человеку.",
    function: "Половой сигнал в сезон",
    state: "Течка / поиск партнёра",
    confidence: 0.78,
    why: "Шёц: брачный крик — длинные серии весной, иногда похожи на плач младенца. Это не мяу у миски.",
    not_a_fact: "Без сезона легко спутать с воем.",
    weak: 0,
    sources: ["schotz2017", "schotz2019"],
  },
  {
    id: "cat_meow_cuddle",
    species_id: "cat",
    sound_id: "meow",
    context_id: "cuddle",
    behavior_id: null,
    gloss:
      "Мяу во время ласки: просьба продолжить или «хватит». По одному звуку не ясно, приятно или нет.",
    function: "Мяу во время ласки",
    state: "Контакт; знак неясен",
    confidence: 0.54,
    why: "Шёц и соавт., 2023: ситуация ласки — 38 мяу, 6 кошек, ровная мелодия. Выборка маленькая, поэтому не «я счастлив».",
    not_a_fact: "Не факт удовольствия.",
    weak: 1,
    sources: ["schotz2023", "schotz2019"],
  },
  {
    id: "cat_meow_lift",
    species_id: "cat",
    sound_id: "meow",
    context_id: "lifting",
    behavior_id: null,
    gloss: "Мяу, когда берут на руки: согласие или протест. Нужен язык тела.",
    function: "Реакция на удержание человеком",
    state: "Неоднозначно: в статье кошку держат охотно или нет",
    confidence: 0.5,
    why: "Шёц, 2023: когда берут на руки — 27 мяу, 6 кошек. Авторы прямо пишут: кошку держат охотно или нет. Без поведения перевод слабый.",
    not_a_fact: "Не «не люби меня».",
    weak: 1,
    sources: ["schotz2023"],
  },
  {
    id: "cat_meow_play",
    species_id: "cat",
    sound_id: "meow",
    context_id: "play",
    behavior_id: null,
    gloss: "Возможно игровой запрос, но по мелодии в статье это похоже на переноску.",
    function: "Игра или возбуждение",
    state: "Сильное возбуждение; по высоте голоса не отличить от стресса",
    confidence: 0.5,
    why: "Шёц, 2023: в игре высота голоса в среднем падает, как в переноске. Поэтому игру нельзя ставить как факт без игровых движений.",
    not_a_fact: "Не доказанное «давай играть».",
    weak: 1,
    sources: ["schotz2023"],
  },
  {
    id: "cat_trill_approach",
    species_id: "cat",
    sound_id: "trill",
    context_id: null,
    behavior_id: "approach",
    gloss: "«Привет, подхожу мирно» — трель плюс сближение.",
    function: "Дружеское приветствие",
    state: "Низкая агрессия",
    confidence: 0.84,
    why: "Трель при дружеском подходе — типичная ситуация у Шёц. Сближение усиливает чтение относительно одной только трели.",
    not_a_fact: "Не слово «привет».",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "cat_purr_knead",
    species_id: "cat",
    sound_id: "purr",
    context_id: null,
    behavior_id: "knead",
    gloss: "Контактное мурлыканье с «месит». Ближе к «продолжай», но мурлыканье бывает и при боли.",
    function: "Низкая угроза при тактильном контакте",
    state: "Скорее дружеский контакт, не доказанное счастье",
    confidence: 0.48,
    why: "Сочетание типично для контакта, но Шёц прямо перечисляет мурлыканье при боли и стрессе. Поведение не отменяет эту оговорку.",
    not_a_fact: "Не научный факт «кошка счастлива».",
    weak: 1,
    sources: ["schotz2017"],
  },
  {
    id: "cat_hiss_ears",
    species_id: "cat",
    sound_id: "hiss",
    context_id: null,
    behavior_id: "ears_back",
    gloss: "«Не подходи» — шипение и прижатые уши, защита целиком.",
    function: "Оборонительное предупреждение",
    state: "Страх / защита",
    confidence: 0.9,
    why: "Шипение в списке типов — угрожающий выдох; прижатые уши — тот же набор защиты. Звук и поза согласованы.",
    not_a_fact: "Не приговор о характере.",
    weak: 0,
    sources: ["schotz2017"],
  },
  {
    id: "dog_bark_walk",
    species_id: "dog",
    sound_id: "bark",
    context_id: "walk",
    behavior_id: null,
    gloss: "Лай перед прогулкой: предвкушение, не охрана границы.",
    function: "Возбуждение к выходу с хозяином",
    state: "Не агрессия (у Понграца низкие оценки агрессии, средние — игры и радости)",
    confidence: 0.64,
    why: "Понграц и соавт., 2005: отдельная ситуация «собираются на прогулку» (хозяин берёт поводок). Слушатели не путают её с незнакомцем или нападением по шкале агрессии.",
    not_a_fact: "Не слово «гулять».",
    weak: 0,
    sources: ["pongracz2005"],
  },
  {
    id: "dog_bark_ball",
    species_id: "dog",
    sound_id: "bark",
    context_id: "ball",
    behavior_id: null,
    gloss: "Лай на мяч/игрушку: запрос игры с предметом.",
    function: "Просьба об игрушке",
    state: "Игровое возбуждение, слабее чем полноценная возня",
    confidence: 0.6,
    why: "Шестая ситуация у Понграца, 2005: хозяин дразнит мячом. По шкалам игры и радости — средне, не как на незнакомца.",
    not_a_fact: "Не отдельный «дай мяч»-словарь.",
    weak: 1,
    sources: ["pongracz2005"],
  },
  {
    id: "dog_bark_food",
    species_id: "dog",
    sound_id: "bark",
    context_id: "food_guard",
    behavior_id: null,
    gloss:
      "«Отдай / хочу это» — лай, когда еду или предмет удерживают. Это запрос или фрустрация, не охрана кости.",
    function: "Просьба отдать еду или предмет",
    state: "Возбуждение / фрустрация, не доказанная агрессия",
    confidence: 0.56,
    why: "Ближайшая ситуация у Понграца, 2005 — «мяч»: хозяин не отдаёт предмет, слушатели ставят игру и радость, а не агрессию как у незнакомца. Охрана еды у Фараго — это рычание у кости, не лай.",
    not_a_fact: "Не словарь «дай еду» и не «это моё» из статьи про рычание.",
    weak: 1,
    sources: ["pongracz2005"],
  },
  {
    id: "dog_bark_food_wag",
    species_id: "dog",
    sound_id: "bark",
    context_id: "food_guard",
    behavior_id: "wag_loose",
    gloss:
      "«Дай / давай это» — лай к удерживаемой еде или предмету. Свободный хвост читается как запрос, не как охрана.",
    function: "Запрос к человеку, который не отдаёт еду или предмет",
    state: "Возбуждение без жёсткой угрозы",
    confidence: 0.64,
    why: "Понграц: лай на удерживаемый мяч не путают с агрессией на незнакомца. Свободное виляние не стыкуется с жёсткой стойкой охраны. Рычание у кости у Фараго — другой сигнал и другая ситуация.",
    not_a_fact: "Не факт, что собака «дружелюбна» только из-за хвоста; это не перевод «это моё».",
    weak: 1,
    sources: ["pongracz2005"],
  },
  {
    id: "dog_bark_fight",
    species_id: "dog",
    sound_id: "bark",
    context_id: "fight",
    behavior_id: null,
    gloss: "«Угроза / защита» — лай в ситуации учебного нападения.",
    function: "Угрожающий лай",
    state: "Сильная агрессия, часто ещё и отчаяние",
    confidence: 0.82,
    why: "Понграц, 2005, и повтор 2021: ситуация учебного нападения получает самые высокие оценки агрессии, рядом с незнакомцем.",
    not_a_fact: "Не диагноз «злая собака».",
    weak: 0,
    sources: ["pongracz2005"],
  },
  {
    id: "dog_bark_door_beh",
    species_id: "dog",
    sound_id: "bark",
    context_id: null,
    behavior_id: "at_door",
    gloss: "Лай у двери: ближе к тревоге на чужого (звонок незнакомца), чем к игре.",
    function: "Сигнал у границы дома",
    state: "Высокое возбуждение",
    confidence: 0.74,
    why: "У Ин тревога — незнакомец у двери. Собака у двери — та же ситуация, даже если звонок не назван.",
    not_a_fact: "Не любой лай в квартире.",
    weak: 0,
    sources: ["yin2004", "pongracz2005"],
  },
  {
    id: "dog_bark_wag",
    species_id: "dog",
    sound_id: "bark",
    context_id: null,
    behavior_id: "wag_loose",
    gloss: "Лай и свободное виляние ближе к возбуждению/контакту, чем к угрозе.",
    function: "Возбуждение без жёсткой угрозы",
    state: "Сильное возбуждение; без ситуации не ясно, хорошо это или плохо",
    confidence: 0.46,
    why: "Понграц связывает агрессию с низким частым лаем; свободный хвост — не тот видимый признак, что жёсткая стойка. Без ситуации (игра, еда, дверь) перевод всё равно слабый.",
    not_a_fact: "Виляние ≠ «собака рада» как научный факт.",
    weak: 1,
    sources: ["pongracz2006"],
  },
  {
    id: "dog_bark_stiff",
    species_id: "dog",
    sound_id: "bark",
    context_id: null,
    behavior_id: "stiff",
    gloss: "Жёсткая стойка + лай ближе к агрессии/тревоге, чем к игре.",
    function: "Признак угрозы",
    state: "Сильное возбуждение с угрозой",
    confidence: 0.68,
    why: "Понграц: низкий частый лай люди ставят как агрессию. Жёсткая стойка — согласованный признак позы, не замена записи звука.",
    not_a_fact: "Без записи частоты это не лабораторная ситуация Ин.",
    weak: 1,
    sources: ["pongracz2006", "yin2004"],
  },
  {
    id: "dog_bark_retreat",
    species_id: "dog",
    sound_id: "bark",
    context_id: null,
    behavior_id: "retreat",
    gloss: "Лай с отступлением ближе к страху или одиночеству, чем к нападению.",
    function: "Отступление и голос",
    state: "Страх: и тянет подойти, и хочется отойти",
    confidence: 0.62,
    why: "Высокий протяжный лай у Понграца читают как страх или отчаяние; отступление усиливает это чтение против тревоги на чужого.",
    not_a_fact: "Не доказанная тревога разлуки как диагноз.",
    weak: 1,
    sources: ["pongracz2006"],
  },
  {
    id: "dog_whine_iso",
    species_id: "dog",
    sound_id: "whine",
    context_id: "isolation",
    behavior_id: null,
    gloss: "«Вернись» — скуление в одиночестве, зов к хозяину.",
    function: "Запрос воссоединения",
    state: "Страх / фрустрация разлуки",
    confidence: 0.7,
    why: "Одиночество — отдельная ситуация у Ин (лай) и у Понграца («одна»). Скуление по Мортону — не враждебность; вместе с одиночеством это зов, не охрана.",
    not_a_fact: "Не автоматически «боль».",
    weak: 0,
    sources: ["yin2004", "pongracz2005", "morton1977"],
  },
  {
    id: "dog_growl_stiff",
    species_id: "dog",
    sound_id: "growl",
    context_id: null,
    behavior_id: "stiff",
    gloss: "Рычание и жёсткая стойка: скорее угроза, не игра.",
    function: "Угроза: отойди",
    state: "Защита с угрозой",
    confidence: 0.74,
    why: "Фараго отличает игровое рычание, когда есть игра; без игрового поклона жёсткая стойка ближе к незнакомцу или охране еды. Мортон: низкий резкий звук — враждебность.",
    not_a_fact: "Не приговор, что укусит.",
    weak: 0,
    sources: ["farago2010", "morton1977"],
  },
  {
    id: "chick_food_search",
    species_id: "chicken",
    sound_id: "food_call",
    context_id: null,
    behavior_id: "search_ground",
    gloss:
      "«Здесь еда» — пищевой крик и поиск на земле совпадают с тем, как куры отвечают на запись крика.",
    function: "Указание на корм",
    state: "Обнаружение пищи",
    confidence: 0.9,
    why: "Эванс и Эванс, 1999: после пищевого крика куры ищут корм на земле. Поиск на земле — та же реакция слушателя.",
    not_a_fact: "Не человеческая фраза, но смысл типа «еда».",
    weak: 0,
    sources: ["evans1999", "evans2007"],
  },
  {
    id: "chick_air_up",
    species_id: "chicken",
    sound_id: "aerial",
    context_id: null,
    behavior_id: "look_up",
    gloss: "«Сверху опасность» — воздушная тревога и взгляд вверх / припадание.",
    function: "Воздушная угроза",
    state: "Тревога",
    confidence: 0.9,
    why: "Эванс и соавт., 1993: если проиграть воздушную тревогу, куры припадают, смотрят вверх и бегут в укрытие.",
    not_a_fact: "Не имя «ястреб».",
    weak: 0,
    sources: ["evans1993"],
  },
  {
    id: "chick_ground_vig",
    species_id: "chicken",
    sound_id: "ground",
    context_id: null,
    behavior_id: "vigilant",
    gloss: "«На земле опасность» — наземная тревога и вытянутая стойка.",
    function: "Наземная угроза",
    state: "Тревога, настороженность",
    confidence: 0.9,
    why: "Эванс и соавт., 1993: наземная тревога — вытянутая настороженная стойка, не укрытие как при воздухе.",
    not_a_fact: "Не имя «лиса».",
    weak: 0,
    sources: ["evans1993"],
  },
  {
    id: "chick_food_quality",
    species_id: "chicken",
    sound_id: "food_call",
    context_id: "preferred_food",
    behavior_id: null,
    gloss: "Пищевой крик на предпочитаемый корм: сигнал о качестве, не просто «возбуждение».",
    function: "Указание на лакомый корм",
    state: "Обнаружение предпочтительной пищи",
    confidence: 0.8,
    why: "Марлер, Дафти и Пикерт, 1986, часть I: петух даёт больше пищевых криков на лакомый корм, чем на несъедобный предмет — сведения о качестве корма.",
    not_a_fact: "Не меню с названием продукта.",
    weak: 0,
    sources: ["marler1986a", "evans1999"],
  },
  {
    id: "chick_food_audience",
    species_id: "chicken",
    sound_id: "food_call",
    context_id: "hen_present",
    behavior_id: null,
    gloss: "Пищевой крик при курице рядом: зовёт тех, кто слышит, а не «разговор в пустоту».",
    function: "Пищевой крик с учётом того, кто рядом",
    state: "Нашли корм и подзывают других",
    confidence: 0.72,
    why: "Марлер и соавт., 1986, часть II: с самкой криков больше, с самцом меньше, в одиночестве ещё меньше. Содержание всё ещё «еда», плюс кому кричат.",
    not_a_fact:
      "Не доказанный обман в каждом случае (обман обсуждается отдельно, когда предмета нет).",
    weak: 0,
    sources: ["marler1986b"],
  },
];
